apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: developer-defined-tekton-pipeline-node
  labels:
    apps.tanzu.vmware.com/pipeline: test-node     # (!) required
spec:
  params:
    - name: source-url                       # (!) required
    - name: source-revision                  # (!) required
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        steps:
          - name: test
            image: circleci/node:14-browsers #node
            script: |-
              cd `mktemp -d`

              wget -qO- $(params.source-url) | tar xvz -m

              export CI=true
              npm install
              npm i prom-client
              npm run test
