image:
  repository: ghcr.io/benc-uk/nodejs-demoapp
  tag: latest
  pullPolicy: Always

replicaCount: 3

service:
  targetPort: 3000

secretEnv:
  WEATHER_API_KEY:
    secretName: nodejs-demoapp
    secretKey: weatherKey

env:
  AAD_APP_ID: 129e29d2-6c0a-4dbf-849e-320a3aa93d52
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=76ae0e4d-5b1f-4081-915a-34cd49c8c4c2;IngestionEndpoint=https://uksouth-1.in.applicationinsights.azure.com/;LiveEndpoint=https://uksouth.livediagnostics.monitor.azure.com/"
  REDIS_SESSION_HOST: redis
  
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

ingress:
  enabled: true
  className: nginx
  host: nodejs-demoapp.kube.benco.io
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  tls:
    enabled: true
    secretName: benco-io-cert
